apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
    name: multi-k8s-xyz-tls
spec:
    secretName: multi-k8s-xyz
    issuerRef:
        name: letsencrypt-prod
        kind: ClusterIssuer
    commonName: multi-k8s.it-ops.xyz
    dnsNames:
        - multi-k8s.it-ops.xyz
    acme:
        config:
            - http01:
                ingressClass: nginx
              domains:
                - multi-k8s.it-ops.xyz
